import type { PermissionProfile, PermissionProfileName } from './types.js';

const PROJECT_EXECUTABLES = Object.freeze([
  'bun',
  'bun.exe',
  'corepack',
  'corepack.cmd',
  'git',
  'git.exe',
  'bash',
  'bash.exe',
  'cmd',
  'cmd.exe',
  'powershell',
  'powershell.exe',
  'pwsh',
  'pwsh.exe',
  'sh',
  'sh.exe',
  'python',
  'python.exe',
  'python3',
  'python3.exe',
  'py',
  'py.exe',
  'node',
  'node.exe',
  'npm',
  'npm.cmd',
  'npx',
  'npx.cmd',
  'pnpm',
  'pnpm.cmd',
  'rg',
  'rg.exe',
  'yarn',
  'yarn.cmd',
]);

export const permissionProfiles: Readonly<Record<PermissionProfileName, PermissionProfile>> = Object.freeze({
  safe: Object.freeze({
    name: 'safe',
    defaults: Object.freeze({ READ: 'ALLOW', WRITE: 'ASK', EXECUTE: 'ASK', DANGEROUS: 'DENY' }),
    allowedProjectExecutables: PROJECT_EXECUTABLES,
  }),
  balanced: Object.freeze({
    name: 'balanced',
    defaults: Object.freeze({ READ: 'ALLOW', WRITE: 'ALLOW', EXECUTE: 'ALLOW', DANGEROUS: 'ASK' }),
    allowedProjectExecutables: PROJECT_EXECUTABLES,
  }),
  full: Object.freeze({
    name: 'full',
    defaults: Object.freeze({ READ: 'ALLOW', WRITE: 'ALLOW', EXECUTE: 'ALLOW', DANGEROUS: 'ALLOW' }),
    allowedProjectExecutables: PROJECT_EXECUTABLES,
  }),
  custom: Object.freeze({
    name: 'custom',
    defaults: Object.freeze({ READ: 'ALLOW', WRITE: 'ASK', EXECUTE: 'ASK', DANGEROUS: 'DENY' }),
    allowedProjectExecutables: PROJECT_EXECUTABLES,
  }),
});
