import { describe, expect, it } from 'vitest';

import {
  classifyContextPath,
  createLineDiff,
  DEFAULT_CONTEXT_IGNORE_GLOBS,
  fingerprintContent,
  isGeneratedContent,
  summarizeContextText,
} from './context-economy.js';

describe('context economy policy', () => {
  it('skips vendor and generated paths during automatic discovery but preserves explicit access', () => {
    expect(classifyContextPath('node_modules/pkg/index.js', 'automatic')).toMatchObject({
      discoverable: false,
      tier: 0,
    });
    expect(classifyContextPath('dist/app.js.map', 'automatic')).toMatchObject({
      discoverable: false,
      tier: 0,
    });
    expect(classifyContextPath('node_modules/pkg/index.js', 'explicit')).toMatchObject({
      discoverable: true,
      tier: 3,
    });
    expect(classifyContextPath('.env', 'automatic')).toMatchObject({
      discoverable: true,
      tier: 2,
    });
  });

  it('identifies binary files and generated source without denying explicit reads', () => {
    expect(classifyContextPath('assets/logo.png', 'automatic')).toMatchObject({
      discoverable: false,
      kind: 'binary',
    });
    expect(classifyContextPath('src/client.generated.ts', 'automatic')).toMatchObject({
      discoverable: false,
      kind: 'generated',
    });
    expect(classifyContextPath('src/client.generated.ts', 'explicit')).toMatchObject({
      discoverable: true,
      tier: 3,
    });
    expect(isGeneratedContent('// Code generated by fixture. DO NOT EDIT.\nexport const value = 1;')).toBe(true);
  });

  it('exposes deterministic ignore globs for automatic search', () => {
    expect(DEFAULT_CONTEXT_IGNORE_GLOBS).toEqual(
      expect.arrayContaining([
        '!**/node_modules/**',
        '!**/.git/**',
        '!**/dist/**',
        '!**/build/**',
        '!**/coverage/**',
        '!**/*.map',
      ]),
    );
  });

  it('creates stable summaries and fingerprints', () => {
    const source = `import { readFile } from 'node:fs';\n\nexport function loadConfig() {\n  return readFile;\n}\n`;
    const summary = summarizeContextText(source);

    expect(summary).toMatchObject({
      byteLength: Buffer.byteLength(source, 'utf8'),
      lineCount: 6,
    });
    expect(summary.imports).toContain("node:fs");
    expect(summary.exports).toContain('loadConfig');
    expect(fingerprintContent(source)).toHaveLength(64);
    expect(fingerprintContent(source)).toBe(fingerprintContent(source));
  });

  it('returns a bounded line diff for changed context', () => {
    const diff = createLineDiff('one\ntwo\nthree', 'one\nchanged\nthree\nfour');

    expect(diff).toContain('-two');
    expect(diff).toContain('+changed');
    expect(diff).toContain('+four');
  });
});
